# Generated by Django 6.0.7 on 2026-07-22 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticket_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('no_show', 'No Show')], default='booked', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online Booking'), ('walk_in', 'Walk-In')], default='online', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='core.slot')),
            ],
            options={
                'ordering': ['date', 'ticket_number'],
            },
        ),
    ]
