# Generated by Django 6.0.7 on 2026-07-23

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


def set_notification_users(apps, schema_editor):
    Notification = apps.get_model('core', 'Notification')
    for notification in Notification.objects.select_related('appointment').iterator():
        notification.user_id = notification.appointment.patient_id
        notification.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(set_notification_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
