# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('core', '0007_doctor_accounts_diagnosis_service_rating')]

    operations = [
        migrations.AddField(model_name='doctor', name='bio', field=models.TextField(blank=True)),
        migrations.AddField(model_name='doctor', name='photo_url', field=models.URLField(blank=True)),
    ]
