# Generated by Django 6.0.7 on 2026-07-28 17:50

from django.db import migrations, models


def migrate_simplified_roles_and_statuses(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Appointment = apps.get_model('core', 'Appointment')

    Profile.objects.filter(role__in=['staff', 'super_admin']).update(role='admin')
    Appointment.objects.filter(status='booked').update(status='confirmed')
    Appointment.objects.filter(status='no_show').update(status='cancelled')


def reverse_simplified_roles_and_statuses(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Appointment = apps.get_model('core', 'Appointment')

    Profile.objects.filter(role='admin').update(role='staff')
    Appointment.objects.filter(status='confirmed').update(status='booked')
    Appointment.objects.filter(status='cancelled').update(status='no_show')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointment_treatment_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'created_at']},
        ),
        migrations.RunPython(
            migrate_simplified_roles_and_statuses,
            reverse_simplified_roles_and_statuses,
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='source',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notifications_enabled',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time'), name='unique_doctor_slot_time'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ServiceRating',
        ),
    ]
