name: Django CI

on:
  push:
    branches:
      - main
      - auth-feature
      - admin-feature
      - doctor-feature
      - patient-feature
      - core-feature

  pull_request:
    branches:
      - main
      - auth-feature
      - admin-feature
      - doctor-feature
      - patient-feature
      - core-feature

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: github-actions-secret-key-for-hospital-management-system-2026
      DEBUG: "True"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Check Django configuration
        run: python manage.py check

      - name: Run tests
        run: python manage.py test